name: Suggestion
description: 'Request a mod to add compatibility with!'
title: '[Suggestion]: '
assignees:
  - Fyoncle
labels:
  - suggestion
body:
  - type: input
    id: mod_name
    attributes:
      label: Mod Name
      description: What mod should be added for compatibility?
      placeholder: Mod Menu
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Which parts of the resource pack you specifically thinking it should be added?
      description: A clear explanation of what interfaces this mod contains that is suitable for Icons Compats.
      placeholder: >-
        This mod adds new GUIs that would look great with Icons!
    validations:
      required: true
